version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: whale
      POSTGRES_PASSWORD: whalepass
      POSTGRES_DB: whaletrack
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
