"""create setups table

Revision ID: c11219adc1a0
Revises: 
Create Date: 2025-06-08 01:50:29.618493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c11219adc1a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 #   op.drop_index(op.f('ix_setups_asset'), table_name='setups')
 #   op.drop_index(op.f('ix_setups_id'), table_name='setups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('direction', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('setups_pkey'))
    )
    op.create_index(op.f('ix_setups_id'), 'setups', ['id'], unique=False)
    op.create_index(op.f('ix_setups_asset'), 'setups', ['asset'], unique=False)
    # ### end Alembic commands ###
